name: Run test

on:
  push:
    branches:
      - master

jobs:
  e2e_tests:
    name: E2e Test For Core package
    # needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run e2e Tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        name: 'upload artfact'
        if: success() || failure()
        with:
          name: my-artifacts
          path: ./test/scripts/*.out.txt

      - name: E2E Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: E2E Core Tests Reporter # Name of the check run which will be created
          path: report/e2e-core.xml # Path to test results
          reporter: jest-junit # Format of test results
          fail-on-error: 'true' #  Set action as failed if test report contains any failed test
